lb:
  build: lb/
  ports:
    - "80:80"
  volumes:
    - /var/log/nginx:/var/log/nginx
    - web/:/usr/share/nginx/html/images/

api1:
  image: backln/images.social:1-SNAPSHOT
  ports:
    - "8080:8080"
  environment:
    HTTP_PORT: 8080

api2:
  image: backln/images.social:1-SNAPSHOT
  ports:
    - "8090:8090"
  environment:
    HTTP_PORT: 8090
